spring:
  application:
    name: tomado

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PW}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

# swagger 설정
springdoc:
  swagger-ui:
    groups-order: desc
    default-model-rendering: example
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
    deep-linking: true
    default-model-expand-depth: 2
    default-models-expand-depth: 2
  api-docs:
    path: /tomaDo-docs
  show-actuator: true
  group-configs:
    - group: "user"
      display-name: "User API"
      paths-to-match:
        - "/users/**"
        - "/book/**"
    - group: "memo"
      display-name: "Memo API"
      paths-to-match:
        - "/memos/**"
    - group: "task"
      display-name: "Task API"
      paths-to-match:
        - "/tasks/**"
    - group: "category"
      display-name: "Category API"
      paths-to-match:
        - "/categories/**"
    - group: "shop"
      display-name: "Shop API"
      paths-to-match:
        - "/shop/**"
    - group: "club"
      display-name: "Club API"
      paths-to-match:
        - "/clubs/**"
    - group: "all"
      display-name: "All API"
      paths-to-match:
        - "/**"
  writer-with-default-pretty-printer: true
  use-management-port: false
  packages-to-scan: com.goormthon.tomado.domain.user.controller, com.goormthon.tomado.domain.tomado.controller, com.goormthon.tomado.domain.task.controller ,com.goormthon.tomado.domain.memo.controller, com.goormthon.tomado.domain.club.controller, com.goormthon.tomado.domain.category.controller
  use-fqn: true